{% set name = "sgp4" %}
{% set version = "2.26" %}
{% set sha256 = "48d15763b6af9393fc2024190705588dd3650fcd90133ab980e00bc5607c606e" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/s/sgp4/sgp4-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - setuptools
    - python
  run:
    - python

test:
  requires:
    - numpy *
  imports:
    - sgp4
    - sgp4.tests
  commands:
    - python -m unittest -v sgp4.tests

about:
  home: https://github.com/brandon-rhodes/python-sgp4
  license: MIT
  license_file: {{ environ.RECIPE_DIR }}/LICENSE
  summary: Python implementation of most recent version of the SGP4 satellite tracking algorithm.

  description: |
    Python implementation of most recent version
    of the SGP4 satellite tracking algorithm.

extra:
  recipe-maintainers:
    - jochym
    - brandon-rhodes
